//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esercitazione_GestionePrestitiBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Prestito
    {
        public int IdPrestito { get; set; }

        [Index(IsUnique = true)]
        public int CodiceLibro { get; set; }

        
        public int Matricola { get; set; }

        //formato de daTa
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime DataPrestito { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DataRestituzione { get; set; }

        //chiavi esterne FK

        
        public virtual Libro Libro { get; set; }

        
        public virtual Studente Studente { get; set; }
    }
}
