//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esercitazione_GestionePrestitiBiblioteca.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    

    //la mia classe EF
    public partial class ITS_GestionePrestitiBibliotecaEntities : DbContext
    {
        public ITS_GestionePrestitiBibliotecaEntities()
            : base("name=ITS_GestionePrestitiBibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<Prestito> Prestito { get; set; }
        public virtual DbSet<Studente> Studente { get; set; }
    }
}
